# TODO: replace the title with the name of your restaurant!
title: Jason High quailty Meat 
# TODO: write your restaurateur alter ego name below, or your own name
author: Professor Meat 
# TODO: write your Google Analytics tracking ID below
google_analytics: G-0Z5GSQ9B35 

theme: minima

collections:
  explorations:
    output: true
